"""
Basic usage example of ProteinLM for embedding generation and visualization
"""
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.model_loader import load_model
from src.embedding_generator import ProteinEmbeddingGenerator
from src.visualizer import EmbeddingVisualizer
import numpy as np

def main():
    # Example protein sequences
    sequences = [
        "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH",  # Human HBB
        "MVHLTPEEKTAVNALWGKVNVDAVGGEALGRLLVVYPWTQRFFESFGDLSSPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFSQLSELHCDKLHVDPENFRLLGNVLVCVLARNFGKEFTPQMQAAYQKVVAGVANALAHKYH",  # Human HBD
        "MVHFTAEEKAAVTSLWSKMNVEEAGGEALGRLLVVYPWTQRFFDSFGNLSSPSAILGNPKVKAHGKKVLTSFGDAIKNMDNLKPAFAKLSELHCDKLHVDPENFKLLGNVMVIILATHFGKEFTPEVQAAWQKLVSAVAIALAHKYH",  # Human HBE1
        "MGHFTEEDKATITSLWGKVNVEDAGGETLGRLLVVYPWTQRFFDSFGNLSSASAIMGNPKVKAHGKKVLTSLGDAIKHLDDLKGTFAQLSELHCDKLHVDPENFKLLGNVLVTVLAIHFGKEFTPEVQASWQKMVTGVASALSSRYH",  # Human HBG2
        "MSLTKTERTIIVSMWAKISTQADTIGTETLERLFLSHPQTKTYFPHFDLHPGSAQLRAHGSKVVAAVGDAVKSIDDIGGALSKLSELHAYILRVDPVNFKLLSHCLLVTLAARFPADFTAEAHAAWDKFLSVVSSVLTEKYR",  # Human HBZ
        "MVHLTDAEKATVSGLWGKVNADNVGAEALGRLLVVYPWTQRYFSKFGDLSSASAIMGNPQVKAHGKKVINAFNDGLKHLDNLKGTFAHLSELHCDKLHVDPENFRLLGNMIVIVLGHHLGKEFTPCAQAAFQKVVAGVASALAHKYH",  # Rat Hbb
        "MVHLTDAEKAAVNGLWGKVNPDDVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPKVKAHGKKVINAFNDGLKHLDNLKGTFAHLSELHCDKLHVDPENFRLLGNMIVIVLGHHLGKEFTPCAQAAFQKVVAGVASALAHKYH",  # Rat Hbb
        "MVLSADDKTNIKNCWGKIGGHGGEYGEEALQRMFAAFPTTKTYFSHIDVSPGSAQVKAHGKKVADALAKAADHVEDLPGALSTLSDLHAHKLRVDPVNFKFLSHCLLVTLACHHPGDFTPAMHASLDKFLASVSTVLTSKYR",  # Rat Hba1
        "MSLMKNERAIIMSMWDKMAPHAEPIGTETLERLFSSYPQTKTYFPHFDLHHGSQQLRAHGSKILAAVGDAVKNIDNLSGALTKLSELHAYILRVDPVNFKLLSHCLLVTLAAHFPADFTPEVHEAWDKFMSILSSVLTEKYR",  # Rat Hbz
        "MLTAEEKAAVTAFWGKVKVDEVGGEALGRLLVVYPWTQRFFESFGDLSTADAVMNNPKVKAHGKKVLDSFSNGMKHLDDLKGTFAALSELHCDKLHVDPENFKLLGNVLVVVLARNFGKEFTPVLQADFQKVVAGVANALAHRYH",  # Rat Hbe1
        "MVLSAADKGNVKAAWGKVGGHAAEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGAKVAAALTKAVEHLDDLPGALSELSDLHAHKLRVDPVNFKLLSHSLLVTLASHLPSDFTPAVHASLDKFLANVSTVLTSKYR",  # Bovine HBA
        "MLTAEEKAAVTAFWGKVKVDEVGGEALGRLLVVYPWTQRFFESFGDLSTADAVMNNPKVKAHGKKVLDSFSNGMKHLDDLKGTFAALSELHCDKLHVDPENFKLLGNVLVVVLARNFGKEFTPVLQADFQKVVAGVANALAHRYH",  # Bovine HBB
        "MLSAQERAHITQVWDLIAGHEAPFGAELLRRLFTVYPSTKVYFRHLGDHPDEVQLLSHGQRMLQAVGVAVQYMDNLRAVLSPLADLHAQVLRVDPTNFPLVIQCFQVVLASHLQGEFTVEMQAAWDKFLTGVAVVLTEKYR",  # Bovine HBM
        "MVHFTTEEKAAVASLWAKVNVEVVGGESLARLLIVYPWTQRFFDSFGNLYSESAIMGNPKVKAHGRKVLNSFGNAIEHMDDLKGTFADLSELHCDKLHVDPENFRLLGNMILIVLATHFSKEFTPQMQASWQKLTNAVANALAHKYH",  # Bovine HBE4
        "MVHFTTEENVAVASLWAKVNVEVVGGESLARLLIVCPWTQRFFDSFGNLYSESAIMGNPKVKVYGRKVLNSFGNAIKHMDDLKGTFADLSELHCDKLHVDPENFRLLGNMILIVLATHFSKEFTPQMQAAWQKLTNAVANALTHKYH",  # Bovine HBE2
    ]
    
    # Load model
    tokenizer, model = load_model("Rostlab/prot_t5_xl_half_uniref50-enc")
    
    # Initialize embedding generator
    embedding_generator = ProteinEmbeddingGenerator(model, tokenizer)
    
    # Generate embeddings
    embeddings = embedding_generator.generate_embeddings_batch(sequences)
    print(f"Generated embeddings with shape: {embeddings.shape}")
    
    # Initialize visualizer
    labels = ["Human", "Human", "Human", "Human", "Human",
               "Rat", "Rat", "Rat", "Rat", "Rat",
               "Bovine", "Bovine", "Bovine", "Bovine", "Bovine"]
    visualizer = EmbeddingVisualizer(embeddings, labels)
    
    # Run dimensionality reduction and plot
    # PCA
    pca_embeddings = visualizer.run_pca()
    visualizer.plot_2d(pca_embeddings, title="Protein Embeddings", method="PCA",
                       save_path="protein_embeddings_pca.png")
    
    # UMAP
    umap_embeddings = visualizer.run_umap()
    visualizer.plot_2d(umap_embeddings, title="Protein Embeddings", method="UMAP",
                       save_path="protein_embeddings_umap.png")

if __name__ == "__main__":
    main()